openapi: 3.0.3
info:
  version: "1.0.0"
  title: Chan Zuckerberg Initiative cellxgene Gene Info API
  description: >-
    This API is for internal use to access information from NCBI's E-Utilities API about a given gene.
servers:
  - description: Local
    url: /
  - description: Production environment
    url: https://api.cellxgene.cziscience.com/
  - description: Development environment
    url: https://api.dev.single-cell.czi.technology/
  - description: Staging environment
    url: https://api.staging.single-cell.czi.technology/

paths:
  /v1/gene_info:
    get:
      summary: Given a gene ensembl ID, returns that gene's summary information, full name, synonyms, and NCBI URL. Gene name is only used if the ensembl ID is missing, in order to manually search the gene ensembl ID from its name.
      description: >-
      tags:
        - gene_info
      operationId: backend.gene_info.api.v1.gene_info
      parameters: 
        - $ref: '#/components/parameters/Gene'
        - $ref: '#/components/parameters/GeneID'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneInfo'
        "403":
          $ref: "#/components/responses/403"
        "404":
          $ref: "#/components/responses/404"

components:
  schemas:
    problem:
      type: object
      description: Error message container for HTTP APIs.
      properties:
        type:
          type: string
        title:
          type: string
        detail:
          type: string
    GeneInfo:
      type: object
      properties:
        summary:
          type: string
        name:
          type: string
        synonyms:
          type: array
          items:
            type: string
        ncbi_url:
          type: string
        show_warning_banner:
          type: boolean
  
  parameters: 
    Gene:
      name: gene
      in: query
      description: Specifies the gene name of the gene to search
      schema:
        type: string
    GeneID:
      name: geneID
      in: query
      description: Specifies the ensembl ID of the gene to search
      schema:
        type: string

  responses:
    200:
      description: OK.
    403:
      description: Unauthorized.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/problem"
    404:
      description: Resource not found.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/problem"