openapi: 3.0.3
info:
  version: "1.0.0"
  title: Chan Zuckerburg Initiative cellxgene Where's My Gene (WMG) API
  description: >-
    This API is for internal use only by WMG web client.
servers:
  - description: Local
    url: /
  - description: Production environment
    url: https://api.cellxgene.cziscience.com/
  - description: Development environment
    url: https://api.dev.single-cell.czi.technology/
  - description: Staging environment
    url: https://api.staging.single-cell.czi.technology/

paths:
  /v1/primary_filter_dimensions:
    get:
      summary: Returns the ontology terms for organism and tissue type that can be used when specifying a WMG query.
      description: >-
      tags:
        - wmg
      operationId: backend.wmg.api.v1.primary_filter_dimensions
      parameters: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  snapshot_id:
                    $ref: "#/components/schemas/wmg_snapshot_id"
                  organism_terms:
                    $ref: "#/components/schemas/wmg_ontology_term_id_label_list"
                  tissue_terms:
                  # TODO: specify further: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1967
                  # {"organism_ontology_term_id_0": [ {"tissue_ontology_term_id_0": "tissue_ontology_term_id_0_label"}],}
                    type: object
                  gene_terms:
                    # TODO: specify further: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1967
                    # {"organism_ontology_term_id_0": [ {"gene_ontology_term_id_0": "gene_ontology_term_id_0_label"}],}
                    type: object
        "404":
          $ref: "#/components/responses/404"
  /v1/query:
    post:
      tags:
        - wmg
      operationId: backend.wmg.api.v1.query
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                filter:
                  type: object
                  required:
                    - gene_ontology_term_ids
                    - organism_ontology_term_id
                    - tissue_ontology_term_ids
                  properties:
                      gene_ontology_term_ids:
                        $ref: "#/components/schemas/wmg_ontology_term_id_list"
                      organism_ontology_term_id:
                        type: string
                      tissue_ontology_term_ids:
                        $ref: "#/components/schemas/wmg_ontology_term_id_list"
                      dataset_ids:
                        type: array
                        items:
                          type: string
                          format: uuid
                      disease_ontology_term_ids:
                        $ref: "#/components/schemas/wmg_ontology_term_id_list"
                      sex_ontology_term_ids:
                        $ref: "#/components/schemas/wmg_ontology_term_id_list"
                      development_ontology_stage_term_ids:
                        $ref: "#/components/schemas/wmg_ontology_term_id_list"
                      ethnicity_ontology_term_ids:
                        $ref: "#/components/schemas/wmg_ontology_term_id_list"
                include_filter_dims:
                  type: boolean
                  default: false
              required:
                - filter
      responses:
        "200":
          description: OK
          content:
            application/json:
              example:
                {
                  'snapshot_id': '8ce15034-162a-4e2e-9987-eb1af08bd4d4',
                  'expression_summary': {
                    'gene1': {
                      'tissuetype1': [
                        { 'id': 'CL00000', 'me': 0.0, 'n': 0, 'pc': 0.0, 'tpc': 0.0 },
                        { 'id': 'CL00001', 'me': 0.0, 'n': 0, 'pc': 0.0, 'tpc': 0.0 },
                        { 'id': 'CL00002', 'me': 0.0, 'n': 0, 'pc': 0.0, 'tpc': 0.0 }
                      ],
                      'tissuetype2': [
                        { 'id': 'CL00000', 'me': 0.0, 'n': 0, 'pc': 0.0, 'tpc': 0.0 },
                        { 'id': 'CL00001', 'me': 0.0, 'n': 0, 'pc': 0.0, 'tpc': 0.0 },
                        { 'id': 'CL00002', 'me': 0.0, 'n': 0, 'pc': 0.0, 'tpc': 0.0 }
                      ]
                    },
                    'gene2': {
                      'tissuetype1': [
                        { 'id': 'CL00000', 'me': 0.0, 'n': 0, 'pc': 0.0, 'tpc': 0.0 },
                        { 'id': 'CL00001', 'me': 0.0, 'n': 0, 'pc': 0.0, 'tpc': 0.0 },
                        { 'id': 'CL00002', 'me': 0.0, 'n': 0, 'pc': 0.0, 'tpc': 0.0 }
                      ],
                      'tissuetype2': [
                        { 'id': 'CL00000', 'me': 0.0, 'n': 0, 'pc': 0.0, 'tpc': 0.0 },
                        { 'id': 'CL00001', 'me': 0.0, 'n': 0, 'pc': 0.0, 'tpc': 0.0 },
                        { 'id': 'CL00002', 'me': 0.0, 'n': 0, 'pc': 0.0, 'tpc': 0.0 }
                      ]
                    }
                  },
                  'term_id_labels': {
                    'cell_types': [
                      { 'CL00000': 'CL00000_label' },
                      { 'CL00001': 'CL00001_label' },
                      { 'CL00002': 'CL00002_label' }
                    ],
                    'genes': [
                      { 'gene1': 'gene1_label' },
                      { 'gene2': 'gene2_label' }
                    ]
                  }
                }
              schema:
                type: object
                required:
                  - expression_summary
                  - term_id_labels
                properties:
                  snapshot_id:
                    $ref: "#/components/schemas/wmg_snapshot_id"
                  expression_summary:
                    type: object
                    # we use `additionalProperties` instead of `properties`, since the object's property names are
                    # ontology term ids, rather than a fixed set of names
                    additionalProperties:
                      description: ->
                        One property per gene, where the gene ontology term id is the property name, and the property
                        value is an object of tissue types.
                      type: object
                      # we use `additionalProperties` instead of `properties`, since the object's property names are
                      # ontology term ids, rather than a fixed set of names
                      additionalProperties:
                        description: ->
                          One property per tissue type, where the tissue type ontology term id is the property name,
                          and the property value is an ordered array of viz matrix "dots" (data points). The ordering of
                          the array elements (cell types) should be preserved in the client's rendering of this
                          data.
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              description: cell type ontology term id
                              type: string
                            me:
                              description: mean expression
                              type: number
                              format: float
                              maxLength: 4
                            pc:
                              description: percentage of cells expressing gene within this cell type
                              type: number
                              format: float
                              maxLength: 4
                              minimum: 0.0
                              maximum: 100.0
                            tpc:
                              description: perecentage of cells for this cell type within tissue (cell type's cell count / tissue's total cell count)
                              type: number
                              format: float
                              maxLength: 4
                              minimum: 0.0
                              maximum: 100.0
                            n:
                              description: number of expressed cells (non-zero expression) within this cell type
                              type: integer
                              minimum: 0.0
                  term_id_labels:
                    type: object
                    required:
                      - genes
                      - cell_types
                    properties:
                      genes:
                        $ref: "#/components/schemas/wmg_ontology_term_id_label_list"
                      cell_types:
                        type: object
                        # TODO: specify further (grouped by tissue now): https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1967
#                        items:
#                        $ref: "#/components/schemas/wmg_ontology_term_id_label_list"
                  filter_dimensions:
                    type: object
                    properties:
                      datasets:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: string
                              format: uuid
                            label:
                              type: string
                            collection_label:
                              type: string
                            collection_url:
                              type: string
                              format: url
                      disease_terms:
                        $ref: "#/components/schemas/wmg_ontology_term_id_label_list"
                      sex_terms:
                        $ref: "#/components/schemas/wmg_ontology_term_id_label_list"
                      development_stage_terms:
                        $ref: "#/components/schemas/wmg_ontology_term_id_label_list"
                      ethnicity_terms:
                        $ref: "#/components/schemas/wmg_ontology_term_id_label_list"

components:
  schemas:
    problem:
      type: object
      description: Error message container for HTTP APIs.
      properties:
        type:
          type: string
        title:
          type: string
        detail:
          type: string
    wmg_ontology_term_id_label_list:
      description: ->
        An array of ontology term ids and labels, where array elements are single-element objects of the
        form "<id>":"<label>"
      type: array
      items:
        description: ->
          A single-element object with the ontology term id as the element's property name and the ontology term label
          as the element's property value.
        type: object
        # TODO: fix: https://app.zenhub.com/workspaces/single-cell-5e2a191dad828d52cc78b028/issues/chanzuckerberg/single-cell-data-portal/1967
        # `{"<ontology_term_id>": "<ontology_term_label"}`
#        maxProperties: 1
#        additionalProperties:
#          type: string
    wmg_ontology_term_id_list:
      type: array
      items:
        type: string
    wmg_snapshot_id:
      type: string
      format: uuid
  
  parameters: {}

  responses:
    200:
      description: OK.
    201:
      description: Created.
    202:
      description: Accepted
    204:
      description: No Content
    400:
      description: Invalid parameter.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/problem"
    401:
      description: Failed to authenticate.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/problem"
    403:
      description: Unauthorized.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/problem"
    404:
      description: Resource not found.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/problem"
    405:
      description: Method not allowed.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/problem"
    409:
      description: File conflict.
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/problem"
    413:
      description: Exceed File Size Limit
      content:
        application/problem+json:
          schema:
            $ref: "#/components/schemas/problem"

  securitySchemes: {}
