/**
 * NOTE: If you modify this file, you must update Plausible custom event page for
 * both staging and prod environments as well.
 * Staging: https://plausible.io/cellxgene.staging.single-cell.czi.technology/settings/goals
 * Prod: https://plausible.io/cellxgene.cziscience.com/settings/goals
 */
export enum EVENTS {
  FILTER_SELECT_ASSAY = "FILTER_SELECT_ASSAY",
  FILTER_SELECT_AUTHORS = "FILTER_SELECT_AUTHORS",
  FILTER_SELECT_CELL_COUNT = "FILTER_SELECT_CELL_COUNT",
  FILTER_SELECT_CELL_TYPE = "FILTER_SELECT_CELL_TYPE",
  FILTER_SELECT_DEVELOPMENT_STAGE = "FILTER_SELECT_DEVELOPMENT_STAGE",
  FILTER_SELECT_DISEASE = "FILTER_SELECT_DISEASE",
  FILTER_SELECT_ETHNICITY = "FILTER_SELECT_ETHNICITY",
  FILTER_SELECT_GENE_COUNT = "FILTER_SELECT_GENE_COUNT",
  FILTER_SELECT_ORGANISM = "FILTER_SELECT_ORGANISM",
  FILTER_SELECT_PUBLICATION_DATE = "FILTER_SELECT_PUBLICATION_DATE",
  FILTER_SELECT_SEX = "FILTER_SELECT_SEX",
  FILTER_SELECT_TISSUE = "FILTER_SELECT_TISSUE",
  WMG_SELECT_GENE = "WMG_SELECT_GENE",
  WMG_SELECT_ORGANISM = "WMG_SELECT_ORGANISM",
  WMG_SELECT_TISSUE = "WMG_SELECT_TISSUE",
  WMG_CLICK_NAV = "WMG_CLICK_NAV",
  WMG_HEATMAP_LOADED = "WMG_HEATMAP_LOADED",
}
