export enum EVENTS {
  WMG_SELECT_GENE = "WMG_SELECT_GENE",
  WMG_SELECT_ORGANISM = "WMG_SELECT_ORGANISM",
  WMG_SELECT_TISSUE = "WMG_SELECT_TISSUE",
  WMG_CLICK_NAV = "WMG_CLICK_NAV",
  WMG_HEATMAP_LOADED = "WMG_HEATMAP_LOADED",
}
