ARG BASE_TAG=branch-main

FROM ghcr.io/chanzuckerberg/corpora-upload-base:$BASE_TAG

# Install cellxgene so we get the remote server that has the converter in it
# The cellxgene install script expects executables named python and pip, not python3 and pip3
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1 \
  && update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

# For lighter weight Docker images
ENV PIP_NO_CACHE_DIR=1

# Install python dependencies
# Remove packaging dependency once pyparser>3 is supported.
RUN pip3 install python-igraph==0.8.3 louvain==0.7.0 packaging==21.0 awscli


COPY /python_dependencies/processing/ .

RUN pip3 install -r requirements.txt

# Uninstall cellxgene-schema and install a pinned version of cellxgene-schema if we're running a dev migration
RUN if [ "$HAPPY_BRANCH" = "dev" ] ; then \
        pip3 uninstall cellxgene-schema && \
        pip3 install git+https://github.com/chanzuckerberg/single-cell-curation/@main#subdirectory=cellxgene_schema_cli \
    ;

ADD backend/__init__.py backend/__init__.py
ADD backend/layers backend/layers
ADD backend/common backend/common

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT=""
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}

CMD ["python3", "-m", "backend.layers.processing.process"]
