ARG BASE_TAG=branch-main

FROM python:3.9
RUN apt-get update && apt-get -y install postgresql-client


COPY backend/__init__.py ./backend/__init__.py
COPY backend/corpora/__init__.py ./backend/corpora/__init__.py
COPY backend/corpora/sync_env_with_prod/ ./backend/corpora/sync_env_with_prod/

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT=""
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}

CMD ["backend.corpora.sync_env_with_prod.app.copy_relational_db"]
