ARG BASE_TAG=branch-main

FROM python:3.9
RUN /usr/local/bin/python -m pip install --upgrade pip

RUN apt update && apt -y install graphviz graphviz-dev

RUN pip3 install awscli

# For lighter weight Docker images
ENV PIP_NO_CACHE_DIR=1


WORKDIR /
ADD backend/__init__.py /backend/__init__.py
ADD backend/wmg /backend/wmg
ADD backend/corpora /backend/corpora

# RUN pip3 install -r /backend/wmg/requirements.txt

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT=""
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}

CMD ["python3", "-m", "backend.wmg.data.cube_pipeline"]