ARG BASE_TAG=branch-main

FROM python:3.9
RUN /usr/local/bin/python -m pip install --upgrade pip

RUN apt update && apt -y install graphviz graphviz-dev

RUN pip3 install awscli

# For lighter weight Docker images
ENV PIP_NO_CACHE_DIR=1

WORKDIR /single-cell-data-portal

ADD backend/__init__.py single-cell-data-portal/backend/__init__.py
ADD backend/wmg single-cell-data-portal/backend/wmg
ADD backend/corpora single-cell-data-portal/backend/corpora
ADD backend/ontology_files single-cell-data-portal/backend/ontology_files

RUN pip3 install -r single-cell-data-portal/backend/wmg/requirements.txt

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT=""
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}

CMD ["python3", "-m", "single-cell-data-portal.backend.wmg.data.cube_pipeline"]