FROM public.ecr.aws/lambda/python:3.8

COPY backend/api/data_portal/upload_failures/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY backend/api/data_portal/upload_failures .
COPY backend/__init__.py ./backend/__init__.py
COPY backend/api/data_portal/__init__.py ./backend/api/data_portal/__init__.py
COPY backend/api/data_portal/common ./backend/api/data_portal/common
COPY backend/api/data_portal/dataset_processing ./backend/api/data_portal/dataset_processing
COPY backend/api/data_portal/lambdas/upload_failures ./backend/api/data_portal/upload_failures

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT=""
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}

CMD ["app.handle_failure"]
