ARG BASE_TAG=branch-main

FROM ghcr.io/chanzuckerberg/corpora-upload-base:$BASE_TAG

# Install cellxgene so we get the remote server that has the converter in it
# The cellxgene install script expects executables named python and pip, not python3 and pip3
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1 \
  && update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

# For lighter weight Docker images
ENV PIP_NO_CACHE_DIR=1

# Install python dependencies
# Remove packaging dependency once pyparser>3 is supported.
RUN pip3 install scanpy==1.6.0 python-igraph==0.8.3 louvain==0.7.0 packaging==21.0 awscli


ADD requirements.txt requirements-base.txt
ADD backend/portal/pipeline/processing/requirements.txt requirements-processing.txt
RUN pip3 install -r requirements-base.txt -r requirements-processing.txt

ADD tests /single-cell-data-portal/tests
ADD backend/__init__.py backend/__init__.py
ADD backend/portal/pipeline/__init__.py backend/portal/pipeline/__init__.py
ADD backend/portal/pipeline/processing backend/portal/pipeline/processing
ADD backend/layers backend/layers
ADD backend/common backend/common

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT=""
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}

CMD ["python3", "-m", "backend.layers.processing.process"]