FROM public.ecr.aws/lambda/python:3.8

COPY backend/apps/upload_success .
COPY backend/__init__.py ./backend/__init__.py
COPY backend/apps/__init__.py ./backend/apps/__init__.py
COPY backend/apps/common ./backend/apps/common
COPY backend/apps/dataset_processing ./backend/apps/dataset_processing

RUN pip3 install -r requirements.txt

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT=""
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}

CMD ["app.success_handler"]
