FROM ubuntu:22.04

ENV APP_NAME=corpora-api
ENV EXPORT_ENV_VARS_TO_LAMBDA="APP_NAME DEPLOYMENT_STAGE"
ENV LC_ALL=C.UTF-8
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y python3 libhdf5-dev python3-h5py gettext moreutils build-essential libxml2-dev python3-dev python3-pip zlib1g-dev python3-requests python3-aiohttp llvm jq && \
    rm -rf /var/lib/apt/lists/*

# Don't re-run pip install unless either requirements.txt has changed.
WORKDIR /single-cell-data-portal
ADD requirements-backend.txt requirements-backend.txt

# TODO(prathap): Determine if cmake is really needed for ddtrace
RUN python3 -m pip install cmake
RUN python3 -m pip install -r requirements-backend.txt
EXPOSE 5000

# Install utilities to /single-cell-data-portal so we can run db migrations.
ADD tests /single-cell-data-portal/tests
ADD scripts /single-cell-data-portal/scripts
ADD backend /single-cell-data-portal/backend
ADD container_init.sh /single-cell-data-portal/container_init.sh

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT=""
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}

# For Datadog <-> gunicorn integration
# https://docs.datadoghq.com/containers/docker/integrations/?tab=docker#configuration
# https://docs.datadoghq.com/integrations/gunicorn/#metric-collection
LABEL "com.datadoghq.ad.check_names"='["gunicorn"]'
LABEL "com.datadoghq.ad.init_configs"='[{}]'
LABEL "com.datadoghq.ad.instances"='[{ "proc_name": "backend.api_server.app:app" }]'

ENTRYPOINT ["/single-cell-data-portal/container_init.sh"]
