ARG BASE_TAG=branch-main

FROM python:3.10
RUN /usr/local/bin/python -m pip install --upgrade pip && \
    apt update && apt -y install graphviz graphviz-dev && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get install unzip && \
    apt-get install curl && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install

# For lighter weight Docker images
ENV PIP_NO_CACHE_DIR=1

WORKDIR /

COPY /python_dependencies/wmg_processing/ .
COPY /python_dependencies/common/ .
ARG INSTALL_DEV=false
RUN pip3 install -r requirements.txt
RUN if [ "$INSTALL_DEV" = "true" ]; then python3 -m pip install -r requirements-dev.txt; fi

ADD backend/__init__.py backend/__init__.py
ADD backend/wmg/pipeline backend/wmg/pipeline
ADD backend/common backend/common

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT=""
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}

CMD ["python3", "-m", "backend.wmg.pipeline.pipeline"]
