FROM public.ecr.aws/lambda/python:3.8
RUN yum install -y postgresql

COPY backend/corpora/sync_env_with_prod ./backend/corpora/sync_env_with_prod
COPY backend/corpora/common ./backend/corpora/common

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT=""
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}

CMD ["app.copy_relational_db"]
