ARG BASE_TAG=branch-main

# Note: versions after 20211215 will have a Seurat version which is incompatible with our code
# Do not change this until the underlying issue is fixed
FROM ghcr.io/chanzuckerberg/corpora-upload-base:20211215
# Install cellxgene so we get the remote server that has the converter in it
# The cellxgene install script expects executables named python and pip, not python3 and pip3
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.8 1 \
  && update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

# For lighter weight Docker images
ENV PIP_NO_CACHE_DIR=1

# Install python dependencies
# Remove packaging dependency once pyparser>3 is supported.
RUN pip3 install scanpy==1.6.0 python-igraph==0.8.3 louvain==0.7.0 packaging==21.0 awscli
RUN pip3 install cellxgene-schema==2.1.0

ADD requirements.txt requirements.txt
ADD backend/api/requirements.txt backend/api/requirements.txt
RUN pip3 install -r requirements.txt

ADD tests /corpora-data-portal/tests
ADD backend/__init__.py backend/__init__.py
ADD backend/api/__init__.py backend/api/__init__.py
ADD backend/api/data_portal/dataset_processing backend/api/data_portal/dataset_processing
ADD backend/api/data_portal/common backend/api/data_portal/common

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT=""
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}

CMD ["python3", "-m", "backend.api.data_portal.dataset_processing.process"]
