FROM public.ecr.aws/lambda/python:3.10

# Update AWS root Certificates
ADD https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem /etc/ssl/certs/rds-global-bundle.pem

COPY backend/layers/processing/upload_failures backend/layers/processing/upload_failures
COPY backend/layers/processing/upload_success .
COPY backend/layers ./backend/layers
COPY backend/portal ./backend/portal

COPY /python_dependencies/upload_handler/ .
RUN pip3 install -r requirements.txt

COPY backend/__init__.py ./backend/__init__.py
COPY backend/common ./backend/common

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT=""
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}

CMD ["app.success_handler"]
