ARG BASE_TAG=branch-main

FROM python:3.11
RUN /usr/local/bin/python -m pip install --upgrade pip && \
    apt update && apt -y install graphviz graphviz-dev && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get install unzip && \
    apt-get install curl && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install

# For lighter weight Docker images
ENV PIP_NO_CACHE_DIR=1

WORKDIR /

COPY /python_dependencies/wmg/ .
RUN pip3 install -r requirements.txt

ADD backend/__init__.py backend/__init__.py
ADD backend/wmg/__init__.py backend/wmg/__init__.py
ADD backend/wmg/config.py backend/wmg/config.py
ADD backend/wmg/data backend/wmg/data
ADD backend/wmg/pipeline backend/wmg/pipeline
ADD backend/wmg/api backend/wmg/api
ADD backend/cellguide/pipeline backend/cellguide/pipeline
ADD backend/layers backend/layers
ADD backend/common backend/common

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT=""
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}

CMD ["python3", "-m", "backend.wmg.pipeline"]
