ARG BASE_TAG=branch-main

FROM python:3.10
RUN /usr/local/bin/python -m pip install --upgrade pip && \
    apt update && apt -y install graphviz graphviz-dev && \
    rm -rf /var/lib/apt/lists/* && \
    pip3 install awscli

# For lighter weight Docker images
ENV PIP_NO_CACHE_DIR=1

WORKDIR /

# TODO: Update this to use cellguide pipeline's own requirements file when it is made
ADD requirements-wmg-pipeline.txt requirements-wmg-pipeline.txt
RUN pip3 install -r requirements-wmg-pipeline.txt

ADD backend/__init__.py backend/__init__.py
ADD backend/wmg/__init__.py backend/wmg/__init__.py
ADD backend/wmg/config.py backend/wmg/config.py
ADD backend/wmg/data backend/wmg/data
ADD backend/cellguide/pipeline backend/cellguide/pipeline
ADD backend/layers backend/layers
ADD backend/common backend/common

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT=""
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}

CMD ["python3", "-m", "backend.cellguide.pipeline"]
