FROM satijalab/seurat:4.1.0

# Most of these are required for SCE or R packages
RUN apt-get update && apt-get -yq install \
      cpio \
      git \
      jq \
      python3-pip \
      zlib1g-dev \
      libbz2-dev \
      liblzma-dev \
      libcurl4-openssl-dev \
      libglpk-dev \
      libxml2-dev \
      libfontconfig1-dev \
      libharfbuzz-dev \
      libfribidi-dev \
      libpng-dev \
      libtiff5-dev \
      libfreetype6-dev \
      wget \

  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* && \
  # Install R dependencies
  R -e "install.packages('BiocManager')" && \
  R -e "BiocManager::install('SingleCellExperiment')" && \
  # note: Loom format has been deprecated from cellxgene but cellgeni/sceasy has a dependency on LoomExperiment
  #       See https://github.com/cellgeni/sceasy#installation
  R -e "BiocManager::install('LoomExperiment')" && \
  R -e "install.packages(c('devtools', 'igraph'));" && \
  R -e "library(devtools); devtools::install_github('cellgeni/sceasy@v0.0.7')" && \
  R -e "devtools::install_version('SeuratObject', version = '5.0.0', repos = 'http://cran.rstudio.com/')"