FROM public.ecr.aws/lambda/python:3.11

COPY backend/layers/processing/upload_success .
COPY backend/layers ./backend/layers

RUN pip3 install -r requirements.txt

COPY backend/__init__.py ./backend/__init__.py
COPY backend/common ./backend/common

ARG HAPPY_BRANCH="unknown"
ARG HAPPY_COMMIT=""
LABEL branch=${HAPPY_BRANCH}
LABEL commit=${HAPPY_COMMIT}
ENV COMMIT_SHA=${HAPPY_COMMIT}
ENV COMMIT_BRANCH=${HAPPY_BRANCH}

CMD ["app.success_handler"]
