import json

# Generated by
# https://github.com/chanzuckerberg/single-cell-curation/blob/main/notebooks/compute_tissue_and_cell_type_mappings.ipynb
with open("./fixtures/cell_type_ontology_mapping.json") as cell_type_json:
    cell_type_ontology_mapping = json.load(cell_type_json)
with open("./fixtures/tissue_ontology_mapping.json") as tissue_json:
    tissue_ontology_mapping = json.load(tissue_json)

# Generated by https://github.com/chanzuckerberg/single-cell-curation/blob/main/notebooks/compute_ancestor_mapping.ipynb
with open("./fixtures/development_stage_ontology_mapping.json") as development_stage_json:
    development_stage_ontology_mapping = json.load(development_stage_json)
