import json

base_module_path = "backend/corpora/common/utils/ontology_mappings/fixtures"


class _OntologyMapLoader:
    @property
    def cell_type_ontology_mapping(self):
        # Generated by single-cell-data-portal/scripts/compute_tissue_and_cell_type_mappings.ipynb
        with open(f"{base_module_path}/cell_type_ontology_mapping.json") as cell_type_json:
            return json.load(cell_type_json)

    @property
    def tissue_ontology_mapping(self):
        # Generated by single-cell-data-portal/scripts/compute_tissue_and_cell_type_mappings.ipynb
        with open(f"{base_module_path}/tissue_ontology_mapping.json") as tissue_json:
            return json.load(tissue_json)

    @property
    def development_stage_ontology_mapping(self):
        # Generated by
        # https://github.com/chanzuckerberg/single-cell-curation/blob/main/notebooks/compute_ancestor_mapping.ipynb
        with open(f"{base_module_path}/development_stage_ontology_mapping.json") as development_stage_json:
            return json.load(development_stage_json)


ontology_mappings = _OntologyMapLoader()
