export enum ENTITIES {
  COLLECTION = "COLLECTION",
  DATASET = "DATASET",
  USER_INFO = "USER_INFO",
  DATASET_STATUS = "DATASET_STATUS",
  API_KEY = "API_KEY",
  WMG_PRIMARY_FILTER_DIMENSIONS = "WMG_PRIMARY_FILTER_DIMENSIONS",
  WMG_QUERY = "WMG_QUERY",
  WMG_FILTERS_QUERY = "WMG_FILTERS_QUERY",
  WMG_MARKER_GENES = "WMG_MARKER_GENES",
}
