"""redesign

Revision ID: 00_c5aaf6e2ca9e
Create Date: 2023-01-05 16:06:27.723131

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "00_c5aaf6e2ca9e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE SCHEMA persistence_schema")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "Collection",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("version_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("originally_published_at", sa.DateTime(), nullable=True),
        sa.Column("tombstoned", sa.BOOLEAN(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="persistence_schema",
    )
    op.create_table(
        "CollectionVersion",
        sa.Column("version_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("collection_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("owner", sa.String(), nullable=True),
        sa.Column("curator_name", sa.String(), nullable=True),
        sa.Column("publisher_metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("datasets", postgresql.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True),
        sa.PrimaryKeyConstraint("version_id"),
        schema="persistence_schema",
    )
    op.create_table(
        "Dataset",
        sa.Column("dataset_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("dataset_version_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("dataset_id"),
        schema="persistence_schema",
    )
    op.create_table(
        "DatasetArtifact",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("type", sa.Enum("RAW_H5AD", "H5AD", "RDS", "CXG", name="datasetartifacttype"), nullable=True),
        sa.Column("uri", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="persistence_schema",
    )
    op.create_table(
        "DatasetVersion",
        sa.Column("version_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("dataset_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("collection_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("metadata", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column("artifacts", postgresql.ARRAY(postgresql.UUID(as_uuid=True)), nullable=True),
        sa.Column("status", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["persistence_schema.Dataset.dataset_id"],
        ),
        sa.PrimaryKeyConstraint("version_id"),
        schema="persistence_schema",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("DatasetVersion", schema="persistence_schema")
    op.drop_table("DatasetArtifact", schema="persistence_schema")
    op.drop_table("Dataset", schema="persistence_schema")
    op.drop_table("CollectionVersion", schema="persistence_schema")
    op.drop_table("Collection", schema="persistence_schema")
    # ### end Alembic commands ###
    sa.Enum(name="datasetartifacttype").drop(op.get_bind(), checkfirst=False)
    op.execute("DROP SCHEMA persistence_schema")
