"""standardize db fields

Revision ID: 01_2be441104b48
Revises: 00_c5aaf6e2ca9e
Create Date: 2023-01-09 16:40:13.184800

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "01_2be441104b48"
down_revision = "00_c5aaf6e2ca9e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Collection", "tombstoned", new_column_name="tombstone", schema="persistence_schema")
    op.alter_column("CollectionVersion", "version_id", new_column_name="id", schema="persistence_schema")
    op.alter_column("CollectionVersion", "metadata", new_column_name="collection_metadata", schema="persistence_schema")
    op.alter_column("Dataset", "dataset_id", new_column_name="id", schema="persistence_schema")
    op.alter_column("Dataset", "dataset_version_id", new_column_name="version_id", schema="persistence_schema")
    op.alter_column("DatasetVersion", "version_id", new_column_name="id", schema="persistence_schema")
    op.alter_column("DatasetVersion", "metadata", new_column_name="dataset_metadata", schema="persistence_schema")
    op.drop_constraint(
        "DatasetVersion_dataset_id_fkey", "DatasetVersion", schema="persistence_schema", type_="foreignkey"
    )
    op.create_foreign_key(
        "DatasetVersion_id_fkey",
        "DatasetVersion",
        "Dataset",
        ["dataset_id"],
        ["id"],
        source_schema="persistence_schema",
        referent_schema="persistence_schema",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("Collection", "tombstone", new_column_name="tombstoned", schema="persistence_schema")
    op.alter_column("CollectionVersion", "id", new_column_name="version_id", schema="persistence_schema")
    op.alter_column("CollectionVersion", "collection_metadata", new_column_name="metadata", schema="persistence_schema")
    op.alter_column("Dataset", "id", new_column_name="dataset_id", schema="persistence_schema")
    op.alter_column("Dataset", "version_id", new_column_name="dataset_version_id", schema="persistence_schema")
    op.alter_column("DatasetVersion", "id", new_column_name="version_id", schema="persistence_schema")
    op.alter_column("DatasetVersion", "dataset_metadata", new_column_name="metadata", schema="persistence_schema")
    op.drop_constraint("DatasetVersion_id_fkey", "DatasetVersion", schema="persistence_schema", type_="foreignkey")
    op.create_foreign_key(
        "DatasetVersion_dataset_id_fkey",
        "DatasetVersion",
        "Dataset",
        ["dataset_id"],
        ["dataset_id"],
        source_schema="persistence_schema",
        referent_schema="persistence_schema",
    )
    # ### end Alembic commands ###
