"""add_curator

Revision ID: 32f819760df4
Revises: 21_c830a9e1f874
Create Date: 2021-11-22 09:59:28.579807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from backend.common.corpora_orm import StrippedString

revision = "24_32f819760df4"
down_revision = "23_449eea8f5aeb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("curator_name", StrippedString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "curator_name")
    # ### end Alembic commands ###
