"""standardize db fields

Revision ID: 34_2be441104b48
Revises: 33_c5aaf6e2ca9e
Create Date: 2023-01-09 16:40:13.184800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '34_2be441104b48'
down_revision = '33_c5aaf6e2ca9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Collection', sa.Column('tombstone', sa.BOOLEAN(), nullable=True), schema='persistence_schema')
    op.drop_column('Collection', 'tombstoned', schema='persistence_schema')
    op.add_column('CollectionVersion', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), schema='persistence_schema')
    op.drop_column('CollectionVersion', 'version_id', schema='persistence_schema')
    op.add_column('CollectionVersion', sa.Column('collection_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True), schema='persistence_schema')
    op.drop_column('CollectionVersion', 'metadata', schema='persistence_schema')
    op.add_column('Dataset', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), schema='persistence_schema')
    op.drop_column('Dataset', 'dataset_id', schema='persistence_schema')
    op.add_column('Dataset', sa.Column('version_id', postgresql.UUID(as_uuid=True), nullable=True), schema='persistence_schema')
    op.drop_column('Dataset', 'dataset_version_id', schema='persistence_schema')
    op.add_column('DatasetVersion', sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False), schema='persistence_schema')
    op.drop_column('DatasetVersion', 'version_id', schema='persistence_schema')
    op.add_column('DatasetVersion', sa.Column('dataset_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True), schema='persistence_schema')
    op.drop_column('DatasetVersion', 'metadata', schema='persistence_schema')
    op.drop_constraint('DatasetVersion_dataset_id_fkey', 'DatasetVersion', schema='persistence_schema',
                       type_='foreignkey')
    op.create_foreign_key(None, 'DatasetVersion', 'Dataset', ['dataset_id'], ['id'], source_schema='persistence_schema',
                          referent_schema='persistence_schema')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('DatasetVersion', sa.Column('version_id', postgresql.UUID(), autoincrement=False, nullable=False), schema='persistence_schema')
    op.add_column('DatasetVersion', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='persistence_schema')
    op.drop_constraint(None, 'DatasetVersion', schema='persistence_schema', type_='foreignkey')
    op.create_foreign_key('DatasetVersion_dataset_id_fkey', 'DatasetVersion', 'Dataset', ['dataset_id'], ['dataset_id'], source_schema='persistence_schema', referent_schema='persistence_schema')
    op.drop_column('DatasetVersion', 'dataset_metadata', schema='persistence_schema')
    op.drop_column('DatasetVersion', 'id', schema='persistence_schema')
    op.add_column('Dataset', sa.Column('dataset_id', postgresql.UUID(), autoincrement=False, nullable=False), schema='persistence_schema')
    op.add_column('Dataset', sa.Column('dataset_version_id', postgresql.UUID(), autoincrement=False, nullable=True), schema='persistence_schema')
    op.drop_column('Dataset', 'version_id', schema='persistence_schema')
    op.drop_column('Dataset', 'id', schema='persistence_schema')
    op.add_column('CollectionVersion', sa.Column('version_id', postgresql.UUID(), autoincrement=False, nullable=False), schema='persistence_schema')
    op.add_column('CollectionVersion', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='persistence_schema')
    op.drop_column('CollectionVersion', 'collection_metadata', schema='persistence_schema')
    op.drop_column('CollectionVersion', 'id', schema='persistence_schema')
    op.add_column('Collection', sa.Column('tombstoned', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='persistence_schema')
    op.drop_column('Collection', 'tombstone', schema='persistence_schema')
    # ### end Alembic commands ###
