"""harmonize_schema_state_dev

Revision ID: 4ddb19dcc4e8
Revises: fa0950f6df19
Create Date: 2020-08-28 12:49:52.998722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4ddb19dcc4e8"
down_revision = "fa0950f6df19"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dataset", "project_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("dataset", "project_status", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("dataset", "project_status", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("dataset", "project_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
