"""cleanup

Revision ID: 600689e11cf4
Revises: 78103925d379
Create Date: 2021-06-02 13:25:10.889113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "600689e11cf4"
down_revision = "78103925d379"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_associate_property_owner_child_id", table_name="associate_property_owner")
    op.drop_index("ix_associate_property_owner_property_id", table_name="associate_property_owner")
    op.drop_table("associate_property_owner")
    op.drop_table("parent")
    op.drop_index("ix_property_parent_id", table_name="property")
    op.drop_table("property")
    op.drop_table("test")
    op.drop_index("ix_child_parent_id", table_name="child")
    op.drop_table("child")
    op.alter_column("geneset_dataset_link", "dataset_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("geneset_dataset_link", "geneset_id", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(op.f("ix_geneset_dataset_link_dataset_id"), "geneset_dataset_link", ["dataset_id"], unique=False)
    op.create_index(op.f("ix_geneset_dataset_link_geneset_id"), "geneset_dataset_link", ["geneset_id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_geneset_dataset_link_geneset_id"), table_name="geneset_dataset_link")
    op.drop_index(op.f("ix_geneset_dataset_link_dataset_id"), table_name="geneset_dataset_link")
    op.alter_column("geneset_dataset_link", "geneset_id", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("geneset_dataset_link", "dataset_id", existing_type=sa.VARCHAR(), nullable=False)
    op.create_table(
        "child",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("parent_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["parent.id"], name="child_parent_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="child_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_child_parent_id", "child", ["parent_id"], unique=False)
    op.create_table(
        "test",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="test_pkey"),
    )
    op.create_table(
        "property",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("parent_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["parent_id"], ["parent.id"], name="property_parent_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="property_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_index("ix_property_parent_id", "property", ["parent_id"], unique=False)
    op.create_table(
        "parent",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("optional", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="parent_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "associate_property_owner",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("child_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("property_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["child_id"], ["child.id"], name="associate_property_owner_child_id_fkey"),
        sa.ForeignKeyConstraint(["property_id"], ["property.id"], name="associate_property_owner_property_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="associate_property_owner_pkey"),
    )
    op.create_index(
        "ix_associate_property_owner_property_id", "associate_property_owner", ["property_id"], unique=False
    )
    op.create_index("ix_associate_property_owner_child_id", "associate_property_owner", ["child_id"], unique=False)
    # ### end Alembic commands ###
