"""revisions

Revision ID: 78103925d379
Revises: 7685265932f6
Create Date: 2021-04-26 15:19:30.660056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "78103925d379"
down_revision = "7685265932f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dataset", sa.Column("original_id", sa.String(), nullable=True))
    op.add_column("dataset", sa.Column("published", sa.Boolean(), server_default="False"))
    op.execute(f"UPDATE dataset SET published = True WHERE collection_visibility = 'PUBLIC'")
    op.execute(f"UPDATE dataset SET published = False WHERE collection_visibility = 'PRIVATE'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("dataset", "published")
    op.drop_column("dataset", "original_id")
    # ### end Alembic commands ###
