"""create_geneset_table

Revision ID: eaecfd687730
Revises: 5a363594dd06
Create Date: 2021-02-22 13:07:55.919592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = 'eaecfd687730'
down_revision = '5a363594dd06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geneset',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('gene_symbols', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('collection_id', sa.String(), nullable=False),
    sa.Column('collection_visibility', ENUM('PUBLIC', 'PRIVATE', name='collectionvisibility',  create_type=False), nullable=False),
    sa.ForeignKeyConstraint(['collection_id', 'collection_visibility'], ['project.id', 'project.visibility'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geneset_dataset_link',
    sa.Column('geneset', sa.String(), nullable=True),
    sa.Column('dataset', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dataset'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['geneset'], ['geneset.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geneset_dataset_link')
    op.drop_table('geneset')
    # ### end Alembic commands ###
