Description: >
  This deploys a Coropora data portal remote-dev environment
Parameters:
  ImageTag:
    Description: Please provide an image tag
    Type: String
  Priority:
    Description: Listener rule priority number within the given listener
    Type: Number
  StateMachineBucket:
    Description: State Machine Bucket.
    Type: String
  StateMachineKey:
    Description: State Machine Key.
    Type: String

Resources:
  DevEnv:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3.amazonaws.com/sc-happy-corpora-dev/v1.1/dp-entrypoint.yml
      Parameters:
        CustomStackName: !Ref AWS::StackName
        ImageTag: !Ref ImageTag
        Priority: !Ref Priority
        StateMachineBucket: !Ref StateMachineBucket
        StateMachineKey: !Ref StateMachineKey
Outputs:
  FrontendUrl:
    Description: The URL endpoint for the website service
    Value: !GetAtt DevEnv.Outputs.FrontendUrl
  BackendUrl:
    Description: The URL endpoint for the website service
    Value: !GetAtt DevEnv.Outputs.BackendUrl
