CELLGUIDE_PIPELINE_FIXTURES_BASEPATH = "tests/unit/backend/cellguide/pipeline/fixtures/"

CANONICAL_MARKER_GENES_FIXTURE_FILENAME = "canonical_marker_genes.json"
COMPUTATIONAL_MARKER_GENES_FIXTURE_FILENAME = "computational_marker_genes.json"
REFORMATTED_COMPUTATIONAL_MARKER_GENES_FIXTURE_FILENAME = "reformatted_computational_marker_genes.json"
FORMATTED_COMPUTATIONAL_MARKER_GENES_FIXTURE_FILENAME = "formatted_computational_marker_genes.json"
TISSUE_METADATA_FIXTURE_FILENAME = "tissue_metadata.json"
CELLTYPE_METADATA_FIXTURE_FILENAME = "cell_metadata.json"
ONTOLOGY_GRAPH_FIXTURE_FILENAME = "ontology_graph.json"
ONTOLOGY_TREE_TOPLEVEL_FOLDERNAME = "ontology_tree"
CELLTYPE_ONTOLOGY_TREE_STATE_FIXTURE_FILENAME = "all_states_per_cell_type.json"
TISSUE_ONTOLOGY_TREE_STATE_FIXTURE_FILENAME = "all_states_per_tissue.json"
CELLTYPE_TO_TISSUE_MAPPING_FILENAME = "celltype_to_tissue_mapping.json"
SOURCE_COLLECTIONS_FIXTURE_FILENAME = "source_collections.json"
VALID_EXPLORER_CXGS_FIXTURE_FILENAME = "valid_explorer_cxgs.json"
ASCTB_MASTER_SHEET_FIXTURE_FILENAME = "asctb_master_sheet.json"
FAKE_DATASETS_FIXTURE_FILENAME = "fake_curation_api_datasets.json"
FAKE_COLLECTIONS_FIXTURE_FILENAME = "fake_curation_api_collections.json"
