[tool.poetry]
name = "wmg"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"


[build-system]
requires = ["poetry-core==1.8.1"]
build-backend = "poetry.core.masonry.api"
