# automatically generated by the FlatBuffers compiler, do not modify

# namespace: NetEncoding


class TypedFBArray(object):
    NONE = 0
    Float32FBArray = 1
    Int32FBArray = 2
    Uint32FBArray = 3
    Float64FBArray = 4
    JSONEncodedFBArray = 5
    DictEncoded8FBArray = 6
    DictEncoded16FBArray = 7
    DictEncoded32FBArray = 8
    Int16EncodedXFBArray = 9
