name: Build Images

on:
  push:
    branches:
      - main
      - prod
  repository_dispatch:
    types: [build-images-for-staging, build-images-for-prod]
  workflow_dispatch:
  workflow_call:
env:
  # Force using BuildKit instead of normal Docker, required so that metadata
  # is written/read to allow us to use layers of previous builds as cache.
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_REPO: ${{ secrets.ECR_REPO }}/

permissions:
  id-token: write
  contents: read

jobs:
  build_images:
    uses: ./.github/workflows/build-images.yml
    secrets: inherit
