name: "Lint PR Title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5.2.0
        with:
          types: |
            fix
            feat
            chore
            docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
