name: Merge main into staging

on:
  push:
    branches:
      - main

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge main into staging
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout staging
          git pull
          git merge --no-ff main -m "Merge main into staging"
          git push
